import os
import discord
import asyncio
import aiohttp
from config import DISCORD_QUERY_BOT_TOKEN, DISCORD_QUERY_CHANNEL_ID, RAG_BASE_URL
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

if not DISCORD_QUERY_BOT_TOKEN or not DISCORD_QUERY_CHANNEL_ID:
    logger.error("Missing DISCORD_QUERY_BOT_TOKEN or DISCORD_QUERY_CHANNEL_ID in config.")
    exit(1)

# Set up intents
intents = discord.Intents.default()
intents.message_content = True

class QueryBotClient(discord.Client):
    async def on_ready(self):
        logger.info(f"Logged on as {self.user}!")
        logger.info(f"Listening for questions on query channel ID: {DISCORD_QUERY_CHANNEL_ID}")

    async def on_message(self, message):
        # Ignore messages from the bot itself
        if message.author == self.user:
            return

        # Enforce strict channel lock
        if str(message.channel.id) != DISCORD_QUERY_CHANNEL_ID:
            return

        # Only process text questions (skip pure attachments if any drop here)
        query_text = message.content.strip()
        if not query_text:
            return

        logger.info(f"Received query from {message.author.name}: {query_text[:50]}...")
        
        # Show typing indicator while querying backend
        async with message.channel.typing():
            try:
                # Prepare RAG API request payload
                payload = {
                    "query": query_text,
                    "user_id": str(message.author.id)
                }
                headers = {
                    # Future-proofing: If our engine grows to require JWT token
                    "Authorization": "Bearer development_secret_key"
                }
                
                # Fetch answer from RAG engine
                async with aiohttp.ClientSession() as session:
                    async with session.post(f"{RAG_BASE_URL}/query", json=payload, headers=headers) as getattr_resp:
                        if getattr_resp.status == 200:
                            data = await getattr_resp.json()
                            answer = data.get("answer", "No answer generated by engine.")
                            sources = data.get("sources", [])
                            
                            source_names = list(set([s.get("doc_name", "Unknown Source") for s in sources]))
                            if source_names:
                                source_text = "\\n\\n**Sources:**\\n" + "\\n".join([f"- {name}" for name in source_names])
                            else:
                                source_text = "\\n\\n*(No sources cited in KB)*"

                            reply_message = f"{answer}{source_text}"
                            
                            # Discord max message length is 2000
                            if len(reply_message) > 1990:
                                reply_message = reply_message[:1990] + "..."
                            
                            await message.reply(reply_message)
                            logger.info(f"Replied to query from {message.author.name}")
                        else:
                            error_text = await getattr_resp.text()
                            logger.error(f"RAG engine returned {getattr_resp.status}: {error_text}")
                            await message.reply("❌ The Knowledge Engine could understand your query but failed to retrieve an answer (Internal Error).")

            except aiohttp.ClientConnectionError:
                 logger.error("Could not connect to FastAPI Backend.")
                 await message.reply("❌ The Knowledge Engine is currently offline or unreachable.")
            except Exception as e:
                logger.error(f"Error handling query: {str(e)}")
                await message.reply("❌ An unexpected error occurred while processing your question.")

if __name__ == "__main__":
    client = QueryBotClient(intents=intents)
    try:
        client.run(DISCORD_QUERY_BOT_TOKEN)
    except Exception as e:
        logger.error(f"Failed to start Discord Query Bot: {str(e)}")
